### PR TITLE
Handle comma at start or end of quoted field

### PR DESCRIPTION
**Pull request by egroenen**

### CODE REVIEW

**Comment by egroenen** [comment]
FYI @loganm We really shouldn't have prefix'd "trineo_" on the class names in these files, there are a number of broken references because of that. And so whenever using the code you have to go through a cycle of fixing them all up.

**Comment by nathanKramer** [comment]
That's cos the code doesn't compile, not necessarily because a `trineo_` prefix is a bad idea haha. 
That was my fault, when I opened the relevant PR #1 I rushed it and didn't update all the right places.

Do you think a prefix is a bad idea? I think the incentive is for it to be a psuedo package, so that if we were to bring this entire "apex common" repo into a customer's org, it is clearly distinct from that customer's wider codebase, and was not originally authored in that org.

**Comment by nathanKramer** [comment]
Also, if you have fixed the naming mistakes could you open a PR? :)

**Comment by egroenen** [comment]
I fixed the naming mistakes by removing the prefix! I didn't like the prefix anyway. I personally didn't consider the fact that we developed the code to be worthy of a prefix. The file header can say that instead.

**Comment by egroenen** [comment]
BTW. The reason the code works is that we split on comma, and so if there is a comma at the end or start of a quoted field you end up with a field with just a quote by itself. That is our trigger to go to arms. The proper solution is a state machine and no splits - anywhere.

**Comment by nathanKramer** [comment]
@egroenen the prefix also groups the classes together. Closest thing to a folder we've got.

**Comment by loganm** [comment]
Gah, I wasn't watching the repo, so I didn't get any notifications. I'll take a look and merge these soon.

**Pull request merged**
